project:
  type: website
  output-dir: docs
  
website:
  title: "Ching Xian"
  favicon: tired.png
  
  # navigation bar at the top of the web
  navbar:
    logo: tired.png
    background: primary
    search: true
    
    # sub-pages
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Final Project"
        file: finalproject.qmd
      - text: "Project NM2207"
        file: project.qmd
        
  sidebar:
      style: "floating"
      background: light
      contents:
        - href: index.qmd#whatIsFW
          text: How severe is food waste currently?
        - href: index.qmd#totalFWbyRegion
          text: How much food waste is the world generating?
        - href: index.qmd#worldMap 
          text: Which Country Generated the most food waste?
        - href: index.qmd#top10-bottom10
          text: What are the Top 10 and Bottom 10 Countries for Combined<br>per-capita Food Waste?
        - href: index.qmd#closerLook
          text: Let's take a closer look in our home country
        - href: index.qmd#references
          text: References

        
  #footer
  page-footer:
    left: Copyright 2023, Tang Ching Xian
    right: This website is built with help from NM2207 TAs and tutor 
        
preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    theme: 
      - theme.scss
    fontsize: 1.35em
    toc: true
    fig-cap-location: margin
    anchor-sections: true
    reference-location: margin
    grid:
      sidebar-width: 100px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5rem

editor: visual